#!/data/data/com.termux/files/usr/bin/bash

# rm -rf * && rm -rf $PREFIX/var/lib/andistro/ && rm -rf $PREFIX/bin/andistro
extralink="https://raw.githubusercontent.com/andistro/app/main" # Para a versão main

rm -rf storage
termux-setup-storage

# Log de erros
if [ ! -d "$HOME/storage/shared/termux/andistro/logs" ];then
    mkdir -p "$HOME/storage/shared/termux/"
    mkdir -p "$HOME/storage/shared/termux/andistro"
    mkdir -p "$HOME/storage/shared/termux/andistro/distros"
    mkdir -p "$HOME/storage/shared/termux/andistro/logs"
    touch "$HOME/storage/shared/termux/andistro/logs/.nomedia"
fi

# Cria os diretórios necessários
if [ ! -d "$PREFIX/var/lib/andistro/" ];then
	mkdir -p "$PREFIX/var/lib/andistro/"
	mkdir -p "$PREFIX/var/lib/andistro/lib/share/"
	mkdir -p "$PREFIX/var/lib/andistro/lib/share/locales/"
	mkdir -p "$PREFIX/var/lib/andistro/boot/"
fi

if [ -f "$PREFIX/var/lib/andistro/lib/share/global" ]; then
    source $PREFIX/var/lib/andistro/lib/share/global
fi

# Detecta o idioma do sistema
system_icu_locale_code=$(getprop persist.sys.locale)

#Verifica se o andistro está em $HOME
if [ -f "$HOME/andistro" ]; then
    mv "$HOME/andistro" "$PREFIX/bin/andistro"
    rm -rf "$HOME/andistro"
    curl -s -o "$HOME/termos.sh" "${extralink}/termos.sh" > /dev/null 2>&1
    chmod +x "$HOME/termos.sh"
    bash "$HOME/termos.sh"
    andistro -u
fi

# Configurações do Termux
# Verifica se a configuração já foi aplicada
# Adiciona a configuração de teclas extras se não estiver presente
if ! grep -Fq "extra-keys = [['DRAWER','PASTE'],['ESC','/','-','HOME','UP','END','PGUP','KEYBOARD'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN','ENTER']]" ~/.termux/termux.properties; then
    # Aplica os sed
    sed -i "s|^# *extra-keys = \[\['ESC','/','-','HOME','UP','END','PGUP'\], \\\\|extra-keys = [['DRAWER','PASTE'],['ESC','/','-','HOME','UP','END','PGUP','KEYBOARD'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN','ENTER']]|" ~/.termux/termux.properties
    sed -i "s|^#[[:space:]]*\['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]||" ~/.termux/termux.properties

    # Recarrega Termux settings
    termux-reload-settings
fi

#=============================================================================================
# COMANDOS
#=============================================================================================
if [ -z "$1" ]; then

    export USER=$(whoami)
    HEIGHT=0
    WIDTH=100
    CHOICE_HEIGHT=5
    export PORT=1

    OPTIONS=(1 "Instalar"
            2 "Iniciar"
            3 "Atualizar"
            4 "Desinstalar"
            5 "Ver como terminal")

    CHOICE=$(dialog --no-shadow --clear \
        --title "AnDistro" \
        --menu "Escolha uma das opções:" \
        $HEIGHT $WIDTH $CHOICE_HEIGHT \
        "${OPTIONS[@]}" \
        2>&1 >/dev/tty)

    case $CHOICE in
        1)	
            export PORT=1
            OPTIONS=(1 "Debian"
                    2 "Ubuntu"
                    3 "Ver como terminal")

            CHOICE=$(dialog --no-shadow --clear \
                --title "AnDistro" \
                --menu "Escolha uma das opções:" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)
            case $CHOICE in
                1)
                    andistro  -i debian
                    ;;
                2)
                    andistro -i ubuntu
                    ;;
                3)
                    andistro -i
                    ;;
            esac
        ;;
        2)	
            export PORT=1
            OPTIONS=(1 "Debian"
                    2 "Ubuntu"
                    3 "Ver como terminal")

            CHOICE=$(dialog --no-shadow --clear \
                --title "AnDistro" \
                --menu "Escolha uma das opções:" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)
            case $CHOICE in
                1)
                    andistro -s debian
                    ;;
                2)
                    andistro -s ubuntu
                    ;;
                3)
                    andistro -s
                    ;;
            esac
        ;;

        3)
            andistro -u
        ;;

        4)
            export PORT=1
            OPTIONS=(1 "Debian"
                    2 "Ubuntu"
                    3 "Ver como terminal")

            CHOICE=$(dialog --no-shadow --clear \
                --title "AnDistro" \
                --menu "Escolha uma das opções:" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)
            case $CHOICE in
                1)
                    andistro -d debian
                    ;;
                2)
                    andistro -d ubuntu
                    ;;
                3)
                    andistro -d
                    ;;
            esac
        ;;

        5)
            andistro terminal
        ;;
    esac
exit 0
fi

case "$1" in
    -u)

        echo -e "\n$distro_wait"
        update_progress() {
            current_step=$1
            total_steps=$2

            percent=$((current_step * 100 / total_steps))
            bar_length=30
            filled_length=$((percent * bar_length / 100))
            empty_length=$((bar_length - filled_length))

            filled_bar=$(printf "%${filled_length}s" | tr " " "=")
            empty_bar=$(printf "%${empty_length}s" | tr " " " ")

            printf "\r[%s%s] %3d%%" "$filled_bar" "$empty_bar" "$percent"
        }

        total_steps=24  # Número total de etapas que você quer monitorar
        current_step=0

        {
            #1 Atualiza os repositórios
            sleep 1
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #2 Atualiza os repositórios
            pkg update > /dev/null 2>&1
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #3 Instala o bash
            pkg install --option=Dpkg::Options::="--force-confold" bash -y > /dev/null 2>&1
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #4 Instala o openssl
            pkg install --option=Dpkg::Options::="--force-confold" openssl -y > /dev/null 2>&1
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #5 Instala o apt
            pkg install --option=Dpkg::Options::="--force-confold" apt -y > /dev/null 2>&1
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #6 Atualiza os pacotes
            pkg upgrade -y > /dev/null 2>&1
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #7 Verifica se o termux-exec está instalado
            if ! dpkg -l | grep -qw termux-exec; then
                pkg install termux-exec -y > /dev/null 2>&1
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #8 Verifica se o proot está instalado
            if ! dpkg -l | grep -qw proot; then
                pkg install proot -y > /dev/null 2>&1
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #9 Verifica se o x11-repo está instalado
    
            if ! dpkg -l | grep -qw x11-repo; then
                pkg install x11-repo -y > /dev/null 2>&1
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #10 Verifica se o termux-x11-nightly está instalado
            if ! dpkg -l | grep -qw termux-x11-nightly; then
                pkg install termux-x11-nightly -y > /dev/null 2>&1
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #11 Verifica se o pulseaudio está instalado
            if ! dpkg -l | grep -qw pulseaudio; then
                pkg install pulseaudio -y > /dev/null 2>&1
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #12 Verifica se o wget está instalado
            if ! dpkg -l | grep -qw wget; then
                pkg install wget -y > /dev/null 2>&1
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #13 Verifica se o dialog está instalado
            if ! dpkg -l | grep -qw dialog; then
                pkg install dialog -y > /dev/null 2>&1
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #14 Verifica se o tar está instalado
            if ! dpkg -l | grep -qw tar; then
                pkg install tar -y > /dev/null 2>&1
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #15 Verifica se o curl está instalado
            if ! dpkg -l | grep -qw curl; then
                pkg install curl -y > /dev/null 2>&1
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #16 Verifica se o unzip está instalado
            if ! dpkg -l | grep -qw unzip; then
                pkg install unzip -y > /dev/null 2>&1
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #17 Verifica se o xz-utils está instalado
            if ! dpkg -l | grep -qw xz-utils; then
                pkg install xz-utils -y > /dev/null 2>&1
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #18 Verifica se o debootstrap está instalado
            if ! dpkg -l | grep -qw debootstrap; then
                pkg install debootstrap -y > /dev/null 2>&1
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #19 Verifica se o dbus está instalado
            if ! dpkg -l | grep -qw dbus; then
                pkg install dbus -y > /dev/null 2>&1
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #20 Verifica se o pv está instalado
            if ! dpkg -l | grep -qw pv; then
                pkg install pv -y > /dev/null 2>&1
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #21 Verifica e baixa global
            if [ ! -f "$PREFIX/var/lib/andistro/lib/share/global" ]; then
                curl -s -o "$PREFIX/var/lib/andistro/lib/share/global" "${extralink}/config/global" > /dev/null 2>&1
                else
                # Verifica e atualiza o global
                curl -s -o "$PREFIX/var/lib/andistro/lib/share/global.check" "${extralink}/config/global" 2>&1
                if [ -f "$PREFIX/var/lib/andistro/lib/share/global" ] && [ -f "$PREFIX/var/lib/andistro/lib/share/global.check" ]; then
                    if ! cmp -s "$PREFIX/var/lib/andistro/lib/share/global" "$PREFIX/var/lib/andistro/lib/share/global.check"; then
                        rm "$PREFIX/var/lib/andistro/lib/share/global"
                        mv "$PREFIX/var/lib/andistro/lib/share/global.check" "$PREFIX/var/lib/andistro/lib/share/global"
                        chmod +x "$PREFIX/var/lib/andistro/lib/share/global"
                    else
                        rm "$PREFIX/var/lib/andistro/lib/share/global.check"
                    fi
                fi
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #22 Verifica, instala e atualiza o pacote de idiomas.sh
            if [ ! -f "$PREFIX/var/lib/andistro/lib/share/locales/config-locale.sh" ]; then
                curl -s -o "$PREFIX/var/lib/andistro/lib/share/locales/config-locale.sh" "${extralink}/config/locale/install.sh" 2>&1
                chmod +x "$PREFIX/var/lib/andistro/lib/share/locales/config-locale.sh"
                else
                # Verifica e atualiza o global
                curl -s -o "$PREFIX/var/lib/andistro/lib/share/locales/config-locale.check" "${extralink}/config/locale/install.sh" 2>&1
                if [ -f "$PREFIX/var/lib/andistro/lib/share/locales/config-locale.sh" ] && [ -f "$PREFIX/var/lib/andistro/lib/share/locales/config-locale.check" ]; then
                    if ! cmp -s "$PREFIX/var/lib/andistro/lib/share/locales/config-locale.sh" "$PREFIX/var/lib/andistro/lib/share/locales/config-locale.check"; then
                        rm "$PREFIX/var/lib/andistro/lib/share/locales/config-locale.sh"
                        mv "$PREFIX/var/lib/andistro/lib/share/locales/config-locale.check" "$PREFIX/var/lib/andistro/lib/share/locales/config-locale.sh"
                        chmod +x "$PREFIX/var/lib/andistro/lib/share/locales/config-locale.sh"
                    else
                        rm "$PREFIX/var/lib/andistro/lib/share/locales/config-locale.check"
                    fi
                fi
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #23 Verifica se o andistro está em $HOME
            if [ -f "$HOME/andistro" ]; then
                mv "$HOME/andistro" "$PREFIX/bin/andistro"
                rm -rf "$HOME/andistro"
            fi
            chmod +x "$PREFIX/bin/andistro"
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1

            #24 Verifica e atualiza o andistro
            curl -s -o "$HOME/andistro.check" "${extralink}/andistro" 2>&1

            if [ -f "$PREFIX/bin/andistro" ] && [ -f "$HOME/andistro.check" ]; then
                if ! cmp -s "$PREFIX/bin/andistro" "$HOME/andistro.check"; then
                    rm "$PREFIX/bin/andistro"
                    mv "$HOME/andistro.check" "$PREFIX/bin/andistro"
                    chmod +x "$PREFIX/bin/andistro"
                else
                    rm "$HOME/andistro.check"
                fi
            fi
            ((current_step++))
            update_progress "$current_step" "$total_steps"; sleep 0.1
            
            echo  # pular linha no fim
        }

        bash $PREFIX/var/lib/andistro/lib/share/locales/config-locale.sh

        chmod +x "$PREFIX/var/lib/andistro/lib/share/global"
        source "$PREFIX/var/lib/andistro/lib/share/global"
        echo -e "$label_update_finish"
        exit 1
        ;;

    -i)
        if [ -z "$2" ]; then
            echo "$distro_desc_line_1"
            echo ""
            echo "$distro_desc_line_2"
            echo "$distro_desc_line_3"
            echo " "
            echo "$distro_desc_line_8"
            echo "$distro_desc_line_10"
            echo " "
            echo "$distro_desc_line_13"
            echo "   debian"
            echo "   ubuntu"
            exit 1
        fi

        if [ "$2" == "debian" ]; then
            echo "$distro_wait"
            #andistro ${distro_update} 2>&1
            andistro alerta
            show_progress_dialog "wget" "${label_progress}" 1 -O "$PREFIX/var/lib/andistro/boot/install-debian.sh" "${extralink}/distros/debian.sh"
            chmod +x $PREFIX/var/lib/andistro/boot/install-debian.sh
            bash $PREFIX/var/lib/andistro/boot/install-debian.sh
            clear
            andistro -s
            andistro -s debian
            #rm -rf $PREFIX/var/lib/andistro/boot/install-debian.sh
            clear

        elif [ "$2" == "ubuntu" ]; then
            echo "$distro_wait"
            #andistro ${distro_update} 2>&1
            andistro alerta
            show_progress_dialog "wget" "${label_progress}" -O "$PREFIX/var/lib/andistro/boot/install-ubuntu.sh" "${extralink}/distros/ubuntu.sh"
            chmod +x $PREFIX/var/lib/andistro/boot/install-ubuntu.sh
            bash $PREFIX/var/lib/andistro/boot/install-ubuntu.sh
            clear
            andistro -s
            andistro -s ubuntu
            #rm -rf $PREFIX/var/lib/andistro/boot/install-ubuntu.sh
            clear

        else
            echo "Distribuição não reconhecida: $2"
            exit 1
        fi
        ;;
    -d)
        if [ -z "$2" ]; then
            echo "$distro_desc_line_1"
            echo ""
            echo "$distro_desc_line_4"
            echo "$distro_desc_line_5"
            echo " "
            echo "$distro_desc_line_8"
            echo "$distro_desc_line_11"
            echo " "
            echo "$distro_desc_line_13"
            echo "   debian"
            echo "   ubuntu"
            exit 1
        fi

        if [ "$2" == "total" ]; then
            # Desinstalação total
            echo "$distro_wait"
            rm -rf $PREFIX/var/lib/andistro/
            rm -rf $PREFIX/bin/andistro/
            rm -rf /data/data/com.termux/files/usr/var/run/dbus/pid 
            rm -rf system_bus_socket
            
        elif [ "$2" == "debian" ]; then
            echo "$distro_wait"
            rm -rf $PREFIX/var/lib/andistro/boot/debian/
            rm -rf $PREFIX/var/lib/andistro/boot/debian/*
            rm -rf $PREFIX/var/lib/andistro/boot/start-debian*
            rm -rf /data/data/com.termux/files/usr/var/run/dbus/pid 
            rm -rf system_bus_socket
            echo "Desinstalação concluída!"

        elif [ "$2" == "ubuntu" ]; then
            echo "$distro_wait"
            rm -rf $PREFIX/var/lib/andistro/boot/ubuntu/
            rm -rf $PREFIX/var/lib/andistro/boot/ubuntu/*
            rm -rf $PREFIX/var/lib/andistro/boot/start-ubuntu*
            rm -rf /data/data/com.termux/files/usr/var/run/dbus/pid 
            rm -rf system_bus_socket
            echo "Desinstalação concluída!"

        else
            echo "Distribuição não reconhecida: $2"
            exit 1
        fi
        ;;
    -s)
        if [ -z "$2" ]; then
            echo "$distro_desc_line_1"
            echo ""
            echo "$distro_desc_line_6"
            echo "$distro_desc_line_7"
            echo " "
            echo "$distro_desc_line_8"
            echo "$distro_desc_line_12"
            echo " "
            echo "$distro_desc_line_13"
            echo "   debian"
            echo "   ubuntu"
            exit 1
        fi

        if [ "$2" == "debian" ]; then
            echo "$distro_wait"
            bash $PREFIX/var/lib/andistro/boot/start-debian

        elif [ "$2" == "ubuntu" ]; then
            echo "$distro_wait"
            bash $PREFIX/var/lib/andistro/boot/start-ubuntu

        else
            echo "Distribuição não reconhecida: $2"
            exit 1
        fi
        ;;

    terminal)
        echo "$distro_desc_line_1"
        echo ""
        echo "$distro_desc_line_2"
        echo "$distro_desc_line_3"
        echo " "
        echo "$distro_desc_line_4"
        echo "$distro_desc_line_5"
        echo " "
        echo "$distro_desc_line_6"
        echo "$distro_desc_line_7"
        echo " "
        echo "$distro_desc_line_8"
        echo "$distro_desc_line_9"
        echo "$distro_desc_line_10"
        echo "$distro_desc_line_11"
        echo "$distro_desc_line_12"
        echo " "
        echo "$distro_desc_line_13"
        echo "   debian"
        echo "   ubuntu"
        ;;

    alerta)
        {
            for i in {1..50}; do
                sleep 0.1
                echo $((i * 2))
            done
        } | dialog --no-shadow --gauge "${label_distro_alert_timezone_desc} \n$label_distro_alert_timezone_detected $system_timezone\n\n$label_sleep_in_5s" 10 60 0
        ;;
    --set-edit)
        # Comando interno para iniciar a edição direta do código
        if [ -z "$2" ]; then
            # Não foi passado subcomando, comportamento padrão
            nano "$PREFIX/bin/andistro"
        else
            case "$2" in
                debian)
                    nano "$PREFIX/var/lib/andistro/boot/install-debian.sh"
                    ;;
                start-debian)
                    nano "$PREFIX/var/lib/andistro/boot/start-debian"
                    ;;
                ubuntu)
                    nano "$PREFIX/var/lib/andistro/boot/install-ubuntu"
                    ;;
                start-ubuntu)
                    nano "$PREFIX/var/lib/andistro/boot/start-ubuntu.sh"
                    ;;
                module-global)
                    nano "$PREFIX/var/lib/andistro/lib/share/global"
                    ;;
                module-locale)
                    nano "$PREFIX/var/lib/andistro/lib/share/locales_${system_icu_locale_code}.sh"
                    ;;
                *)
                    echo "Subcomando desconhecido: $2"
                    ;;
            esac
        fi
        ;;

    *)
        echo "$distro_command_not_found $1"
        andistro terminal
        exit 1
        ;;
esac