#!/data/data/com.termux/files/usr/bin/bash

rm -rf $HOME/storage
termux-setup-storage

update_progress() {
    current_step=$1
    total_steps=$2

    percent=$((current_step * 100 / total_steps))
    bar_length=30
    filled_length=$((percent * bar_length / 100))
    empty_length=$((bar_length - filled_length))

    filled_bar=$(printf "%${filled_length}s" | tr " " "=")
    empty_bar=$(printf "%${empty_length}s" | tr " " " ")

    printf "\r[%s%s] %3d%%" "$filled_bar" "$empty_bar" "$percent"
}

total_steps=25  # Número total de etapas que você quer monitorar
current_step=0

{
    #1 Atualiza os repositórios
    sleep 1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #2 Atualiza os repositórios
    pkg update > /dev/null 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #3 Instala o bash
    pkg install --no-install-recommends --option=Dpkg::Options::="--force-confold" bash -y > /dev/null 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #4 Instala o openssl
    pkg install --no-install-recommends --option=Dpkg::Options::="--force-confold" openssl -y > /dev/null 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #5 Instala o apt
    pkg install --no-install-recommends --option=Dpkg::Options::="--force-confold" apt -y > /dev/null 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #6 Atualiza os pacotes
    pkg upgrade -y > /dev/null 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #7 Verifica se o termux-exec está instalado
    if ! dpkg -l | grep -qw termux-exec; then
        pkg install --no-install-recommends termux-exec -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #8 Verifica se o proot está instalado
    if ! dpkg -l | grep -qw proot; then
        pkg install --no-install-recommends proot -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #9 Verifica se o x11-repo está instalado
    if ! dpkg -l | grep -qw x11-repo; then
        pkg install --no-install-recommends x11-repo -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #10 Verifica se o termux-x11-nightly está instalado
    if ! dpkg -l | grep -qw termux-x11-nightly; then
        pkg install --no-install-recommends termux-x11-nightly -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #11 Verifica se o pulseaudio está instalado
    if ! dpkg -l | grep -qw pulseaudio; then
        pkg install --no-install-recommends pulseaudio -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #12 Verifica se o wget está instalado
    if ! dpkg -l | grep -qw wget; then
        pkg install --no-install-recommends wget -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #13 Verifica se o dialog está instalado
    if ! dpkg -l | grep -qw dialog; then
        pkg install --no-install-recommends dialog -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #14 Verifica se o tar está instalado
    if ! dpkg -l | grep -qw tar; then
        pkg install --no-install-recommends tar -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #15 Verifica se o curl está instalado
    if ! dpkg -l | grep -qw curl; then
        pkg install --no-install-recommends curl -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #16 Verifica se o unzip está instalado
    if ! dpkg -l | grep -qw unzip; then
        pkg install --no-install-recommends unzip -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #17 Verifica se o xz-utils está instalado
    if ! dpkg -l | grep -qw xz-utils; then
        pkg install --no-install-recommends xz-utils -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #18 Verifica se o debootstrap está instalado
    if ! dpkg -l | grep -qw debootstrap; then
        pkg install --no-install-recommends debootstrap -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #19 Verifica se o dbus está instalado
    if ! dpkg -l | grep -qw dbus; then
        pkg install --no-install-recommends dbus -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #20 Verifica se o pv está instalado
    if ! dpkg -l | grep -qw pv; then
        pkg install --no-install-recommends pv -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #21 Verifica se o git está instalado
    if ! dpkg -l | grep -qw git; then
        pkg install --no-install-recommends git -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #22 Verifica se o inxi está instalado
    if ! dpkg -l | grep -qw inxi; then
        pkg install --no-install-recommends inxi -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #23 Verifica se o rsync está instalado
    if ! dpkg -l | grep -qw rsync; then
        pkg install --no-install-recommends rsync -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #24 Todo o pacote de instalação
    git clone -b alpha https://github.com/andistro/app.git app-andistro_setup  > /dev/null 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #25 Extrai o pacote de instalação
    rm -rf "$HOME/app-andistro_setup/.git"
    rm -rf "$HOME/app-andistro_setup/andistro_setup"
    rm -rf "$HOME/app-andistro_setup/README.md"
    mv -f "$HOME/app-andistro_setup/andistro" "$PREFIX/bin/andistro"
    mv -f "$HOME/app-andistro_setup/termos.sh" "$HOME/termos.sh"
    rsync -a "$HOME/app-andistro_setup/" "$PREFIX/var/lib/andistro/"
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #26 Mover o Andistro
    chmod +x "$PREFIX/bin/andistro"
    chmod +x "$PREFIX/var/lib/andistro/lib/share/global"
    chmod +x $PREFIX/var/lib/andistro/boot/.config/*/bin/*
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    echo
}

rm -rf "$HOME/app-andistro_setup"
rm -rf andistro_setup.zip
rm -rf "$HOME/andistro_setup"

chmod +x "$HOME/termos.sh"
bash "$HOME/termos.sh"

andistro --setup storage
chmod +x "$PREFIX/var/lib/andistro/lib/share/global"
source "$PREFIX/var/lib/andistro/lib/share/global"
echo -e "$label_update_finish"
