#!/data/data/com.termux/files/usr/bin/bash

if [ ! -d "$PREFIX/var/lib/andistro/" ];then
	mkdir -p "$PREFIX/var/lib/andistro/"
	mkdir -p "$PREFIX/var/lib/andistro/lib/share/"
	mkdir -p "$PREFIX/var/lib/andistro/lib/share/locales/"
	mkdir -p "$PREFIX/var/lib/andistro/boot/"
	mkdir -p "$PREFIX/var/lib/andistro/boot/.config/"
	mkdir -p "$PREFIX/var/lib/andistro/boot/.config/debian-based/"
	mkdir -p "$PREFIX/var/lib/andistro/boot/.config/debian-based/bin/"
    mkdir -p "$PREFIX/var/lib/andistro/boot/.config/debian-based/environment/"
	mkdir -p "$PREFIX/var/lib/andistro/boot/.config/debian-based/locale_setup/"
	mkdir -p "$PREFIX/var/lib/andistro/wallpapers/"
fi

update_progress() {
    current_step=$1
    total_steps=$2

    percent=$((current_step * 100 / total_steps))
    bar_length=30
    filled_length=$((percent * bar_length / 100))
    empty_length=$((bar_length - filled_length))

    filled_bar=$(printf "%${filled_length}s" | tr " " "=")
    empty_bar=$(printf "%${empty_length}s" | tr " " " ")

    printf "\r[%s%s] %3d%%" "$filled_bar" "$empty_bar" "$percent"
}

total_steps=28  # Número total de etapas que você quer monitorar
current_step=0

{
    #1 Atualiza os repositórios
    sleep 1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #2 Atualiza os repositórios
    apt update > /dev/null 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #3 Instala o bash
    apt install --option=Dpkg::Options::="--force-confold" bash -y > /dev/null 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #4 Instala o openssl
    apt install --option=Dpkg::Options::="--force-confold" openssl -y > /dev/null 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #5 Instala o apt
    apt install --option=Dpkg::Options::="--force-confold" apt -y > /dev/null 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #6 Atualiza os pacotes
    pkg upgrade -y > /dev/null 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #7 Verifica se o termux-exec está instalado
    if ! dpkg -l | grep -qw termux-exec; then
        apt install termux-exec -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #8 Verifica se o proot está instalado
    if ! dpkg -l | grep -qw proot; then
        apt install proot -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #9 Verifica se o x11-repo está instalado
    if ! dpkg -l | grep -qw x11-repo; then
        apt install x11-repo -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #10 Verifica se o termux-x11-nightly está instalado
    if ! dpkg -l | grep -qw termux-x11-nightly; then
        apt install termux-x11-nightly -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #11 Verifica se o pulseaudio está instalado
    if ! dpkg -l | grep -qw pulseaudio; then
        apt install pulseaudio -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #12 Verifica se o wget está instalado
    if ! dpkg -l | grep -qw wget; then
        apt install wget -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #13 Verifica se o dialog está instalado
    if ! dpkg -l | grep -qw dialog; then
        apt install dialog -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #14 Verifica se o tar está instalado
    if ! dpkg -l | grep -qw tar; then
        apt install tar -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #15 Verifica se o curl está instalado
    if ! dpkg -l | grep -qw curl; then
        apt install curl -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #16 Verifica se o unzip está instalado
    if ! dpkg -l | grep -qw unzip; then
        apt install unzip -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #17 Verifica se o xz-utils está instalado
    if ! dpkg -l | grep -qw xz-utils; then
        apt install xz-utils -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #18 Verifica se o debootstrap está instalado
    if ! dpkg -l | grep -qw debootstrap; then
        apt install debootstrap -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #19 Verifica se o dbus está instalado
    if ! dpkg -l | grep -qw dbus; then
        apt install dbus -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #20 Verifica se o pv está instalado
    if ! dpkg -l | grep -qw pv; then
        apt install pv -y > /dev/null 2>&1
    fi
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #21 Todo o pacote de instalação
    curl -O "https://github.com/andistro/app/releases/download/andistro/andistro_setup.zip" 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #22 Extrai o pacote de instalação
    unzip andistro_setup.zip -d "$HOME" 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #23 Mover o Andistro
    chmod +x "$HOME/andistro_setup/termos.sh" 2>&1
    mv "$HOME/andistro_setup/andistro" "$PREFIX/bin/andistro" 2>&1
    chmod +x "$PREFIX/bin/andistro" 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #24 Mover os arquivos necessários
    mv "$HOME/andistro_setup/config/global" "$PREFIX/var/lib/andistro/lib/share/global" 2>&1
    chmod +x "$PREFIX/var/lib/andistro/lib/share/global" 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #25 Mover os arquivos de localização
    mv "$HOME/andistro_setup/config/locale/l10n_"* "$PREFIX/var/lib/andistro/lib/share/locales/" 2>&1
    chmod +x "$PREFIX/var/lib/andistro/lib/share/locales/"* 2>&1
    update_progress "$current_step" "$total_steps"; sleep 0.1
    ((current_step++))

    #26 Mover os scripts de instalação das distros
    mv "$HOME/andistro_setup/distros/debian.sh" "$PREFIX/var/lib/andistro/boot/install-debian.sh" 2>&1
    mv "$HOME/andistro_setup/distros/ubuntu.sh" "$PREFIX/var/lib/andistro/boot/install-ubuntu.sh" 2>&1
    chmod +x "$PREFIX/var/lib/andistro/boot/install-debian.sh" 2>&1
    chmod +x "$PREFIX/var/lib/andistro/boot/install-ubuntu.sh" 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    #27 Mover os arquivos de configuração das distros baseadas no debian
    mv "$HOME/andistro_setup/configs/debian-based/system-config.sh"* "$PREFIX/var/lib/andistro/boot/.config/debian-based/system-config.sh" 2>&1
    mv "$HOME/andistro_setup/configs/debian-based/app-list-recommends.sh"* "$PREFIX/var/lib/andistro/boot/.config/debian-based/app-list-recommends.sh" 2>&1
    mv "$HOME/andistro_setup/configs/debian-based/environment/"* "$PREFIX/var/lib/andistro/boot/.config/debian-based/environment/" 2>&1
    mv "$HOME/andistro_setup/configs/debian-based/vnc/"* "$PREFIX/var/lib/andistro/boot/.config/debian-based/bin/" 2>&1
    mv "$HOME/andistro_setup/configs/debian-based/locale/"* "$PREFIX/var/lib/andistro/boot/.config/debian-based/locale_setup/" 2>&1
    chmod +x "$PREFIX/var/lib/andistro/boot/.config/debian-based/"* 2>&1
    update_progress "$current_step" "$total_steps"; sleep 0.1
    ((current_step++))

    #28 Mover os wallpapers
    mv "$HOME/andistro_setup/wallpapers/config.sh" "$PREFIX/var/lib/andistro/boot/.config/debian-based/wallpapers.sh" 2>&1
    chmod +x "$PREFIX/var/lib/andistro/boot/.config/debian-based/wallpapers.sh" 2>&1
    ((current_step++))
    update_progress "$current_step" "$total_steps"; sleep 0.1

    echo
}

bash "$HOME/andistro_setup/termos.sh"

#rm -rf "$HOME/andistro_setup"
#rm andistro_setup.zip

andistro --setup storage