#!/bin/sh
source "/usr/local/bin/global_var_fun.sh"

DISPLAY=:99
export DISPLAY=$DISPLAY

# Usa RESOLUTION definida pelo startvnc
: "${RESOLUTION:=1920x1080x24}"

/usr/bin/Xvfb $DISPLAY -screen 0 $RESOLUTION -ac +extension GLX +render -noreset &
sleep 2

# Iniciar XFCE
startxfce4 &

sleep 2

# Iniciar VNC
x11vnc -xkb -noxrecord -noxfixes -noxdamage \
  -display $DISPLAY -forever -bg \
  -rfbauth /root/.vnc/passwd -users root -rfbport 5901 -noshm

echo "Servidor VNC iniciado. Conecte-se em localhost:1"
