#!/bin/bash
source "/usr/local/bin/global_var_fun.sh"

#!/bin/sh
PASS=$(dialog --title "Senha VNC" --insecure --passwordbox "Digite a senha para acesso VNC:" 8 40 3>&1 1>&2 2>&3)

[ $? != 0 ] && echo "Operação cancelada." && exit 1

echo "$PASS" | x11vnc -storepasswd - /root/.vnc/passwd

dialog --msgbox "Senha salva com sucesso." 6 40
clear
