#!/bin/bash
source "/usr/local/bin/andistro/global"

WLAN_IP="$wlan_ip_localhost"
#LD_PRELOAD=/lib/aarch64-linux-gnu/libgcc_s.so.1 vncserver -localhost no -depth 24 -name remote-desktop $GEO :$PORT
vncserver -localhost no -depth 24 -name remote-desktop $GEO :$PORT

if pgrep -x "xfce4-session" > /dev/null; then
    xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s $ESCALA
fi

echo -e "\n${label_startvnc_desc} $USER\n\n
${label_localhost} $HOSTNAME:$PORT / 120.0.0.1:$PORT / $WLAN_IP:$PORT\n\n
$label_vncserver_password_forgot\n"