#!/bin/bash
if ! dpkg -l | grep -qw dialog; then
    apt install dialog -y > /dev/null 2>&1
fi
source "/usr/local/bin/global_var_fun.sh"

while true; do
    dialog --msgbox "$label_vnc_password_input_alert" 20 50
    msgbox_status=$?

    if [ "$msgbox_status" -eq 0 ]; then
        PASSWORD=$(dialog --no-shadow --insecure --passwordbox "$label_vnc_password_input" 20 50 3>&1 1>&2 2>&3)
        if [ $? -eq 0 ]; then
            break
        else
            echo "${label_entry_canceled}"
            exit 1
        fi
    else
        echo "$label_retry (status=$msgbox_status)"
        sleep 0.5
    fi
done

# Salvar a senha no arquivo apropriado
if ! /usr/bin/vncpasswd -f <<<"$PASSWORD"$'\n'"$PASSWORD" > "$HOME/.vnc/passwd"; then
    dialog --no-shadow --title "$label_error" --msgbox "$label_vnc_password_save_failed" 20 50
    exit 1
fi

# Proteger o arquivo com permissão segura
chmod 600 "$HOME/.vnc/passwd"

# Barra de progresso
{
    for ((i = 0; i <= 100; i+=2)); do
        sleep 0.08
        echo $i
    done
} | dialog --no-shadow --gauge "${label_change_password}" 20 50 0
