#!/bin/bash
source "/usr/local/bin/global_var_fun.sh"

LD_PRELOAD=/lib/aarch64-linux-gnu/libgcc_s.so.1 vncserver -localhost no -depth 24 -name remote-desktop $GEO :$PORT
clear
echo "${label_startvnc_desc} $USER"