#!/bin/bash
while true; do
    if [ -f ~/andistro-bridge ] && [ -s ~/andistro-bridge ]; then
        CMD=$(cat ~/andistro-bridge)
        rm ~/andistro-bridge
        sh -c "$CMD" > /dev/null 2>&1  # ← NÃO devolve output pro Debian
    fi
    sleep 0.5
done

